services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    user: root
    ports:
      - "5001:5001"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5001
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
    volumes:
      - mlflow-data:/mlflow
    restart: always

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
      - mlflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "mlflow scikit-learn"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - mlflow-data:/mlflow
    entrypoint: /bin/bash
    command: -c "airflow db upgrade && airflow users create --username airflow --password airflow --firstname a --lastname a --role Admin --email a@a.com && airflow variables set MLFLOW_TRACKING_URI http://mlflow:5001"
    restart: on-failure

  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-init
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "mlflow scikit-learn"
      MLFLOW_TRACKING_URI: http://mlflow:5001
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - mlflow-data:/mlflow
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - airflow-webserver
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "mlflow scikit-learn"
      MLFLOW_TRACKING_URI: http://mlflow:5001
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - mlflow-data:/mlflow
    restart: always

volumes:
  postgres-db-volume:
  mlflow-data:
