{{ config(
    materialized='table',
    pre_hook="USE WAREHOUSE RABBIT_QUERY_WH"
) }}

SELECT
    LABEL,
    COUNT(*) AS TOTAL_EMAILS,
    ROUND(AVG(LENGTH(MESSAGE)), 2) AS AVG_MESSAGE_LENGTH,
    ROUND(AVG(ARRAY_SIZE(SPLIT(MESSAGE, ' '))), 2) AS AVG_WORD_COUNT,
    MIN(LENGTH(MESSAGE)) AS MIN_LENGTH,
    MAX(LENGTH(MESSAGE)) AS MAX_LENGTH,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM {{ source('public', 'RAW_SPAM_EMAILS') }}
GROUP BY LABEL
